# Generated by Django 5.1 on 2024-09-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['pk'], 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
    ]
