# Generated by Django 5.1 on 2024-09-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('bookings', '0002_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='artist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='artists.artist'),
        ),
    ]
