# Generated by Django 5.1 on 2024-09-18 18:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_artist_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='The start time of the booking.')),
                ('end_time', models.DateTimeField(blank=True, help_text='The end time of the booking. Optional.', null=True)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Indicates if the schedule has been confirmed.')),
                ('booking_id', models.OneToOneField(help_text='The booking associated with this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
                'ordering': ['start_time'],
            },
        ),
    ]
