# Generated by Django 5.1 on 2024-10-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_instagram_alter_artist_whatsapp'),
        ('bookings', '0004_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
