# Generated by Django 5.1 on 2024-10-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_instagram_alter_artist_whatsapp'),
        ('bookings', '0005_alter_booking_artist_id_alter_booking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='artist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='artists.artist'),
        ),
    ]
