# Generated by Django 5.1 on 2024-09-07 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Use a simple name, for example: `FirstName LastName`.', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, help_text='This field allows access to the admin panel,by default it `is_active` for artists.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('administrator', 'Administrator')], default='artist', help_text='By default, the role is ARTIST,change it only if you want to escalate permissions.', max_length=20),
        ),
    ]
