# Generated by Django 5.1 on 2024-09-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoo',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tattoos', to='artists.artist'),
        ),
    ]
