# Generated by Django 5.1 on 2024-09-11 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.FileField(blank=True, upload_to='company/')),
                ('description', models.TextField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('tiktok', models.URLField()),
                ('rights', models.TextField()),
                ('location', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'company',
                'ordering': ['pk'],
            },
        ),
    ]
