# Generated by Django 5.1 on 2024-09-16 22:43

import apps.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_faq_price_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='twitch',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[apps.utils.validators.validate_phone]),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='rights',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='tiktok',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
