# Generated by Django 5.1 on 2024-09-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_facebook_remove_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
