# Generated by Django 5.1 on 2024-09-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_price_currency_remove_price_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
