# Generated by Django 5.1 on 2024-09-11 15:59

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Use descriptive and concise names, for example: Traditional, Realism, Minimalist, etc.', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'style',
                'verbose_name_plural': 'styles',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Provide a brief description of your specialization.')),
                ('instagram', models.URLField(blank=True, help_text='Use the full Instagram URL, for example: `https://www.instagram.com/username/`', max_length=100, unique=True)),
                ('whatsapp', models.CharField(blank=True, help_text='Use your full number including the area code, for example: `+1 404 555 1234`.', max_length=12, unique=True)),
                ('is_team', models.BooleanField(default=True, help_text='This field is a filter for the landing page,disable it if you do not want to show this artist.')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('styles', models.ManyToManyField(to='artists.style')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['slug'], name='artists_art_slug_6a2353_idx'), models.Index(fields=['is_team'], name='artists_art_is_team_b6c73b_idx')],
            },
        ),
    ]
