# Generated by Django 5.1 on 2024-09-07 19:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a brief description of your specialization.'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True, help_text='Use the full Instagram URL, for example: `https://www.instagram.com/username/`', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_team',
            field=models.BooleanField(default=True, help_text='This field is a filter for the landing page,disable it if you do not want to show this artist.'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Use your full number including the area code, for example: `+1 404 555 1234`.', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(help_text='Use descriptive and concise names, for example: `Traditional`, `Realism`, `Minimalist`, etc.', max_length=50, unique=True),
        ),
    ]
