# Generated by Django 5.1 on 2024-09-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True, help_text='Use the full Instagram URL, for example: `https://www.instagram.com/username/`', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Use your full number including the area code, for example: `+1 404 555 1234`.', max_length=12),
        ),
    ]
