# Generated by Django 5.1 on 2024-09-07 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='styles',
            field=models.ManyToManyField(to='artists.style'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['slug'], name='artists_art_slug_6a2353_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['is_team'], name='artists_art_is_team_b6c73b_idx'),
        ),
    ]
