# Generated by Django 5.1 on 2024-09-13 15:20

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sku', models.CharField(blank=True, editable=False, help_text='Stock Keeping UnitsUnique code automatically generated for inventory management.', max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('usd', 'United States Dollar'), ('eur', 'Euro'), ('jpy', 'Japanese Yen'), ('gbp', 'British Pound'), ('aud', 'Australian Dollar'), ('cad', 'Canadian Dollar'), ('chf', 'Swiss Franc'), ('cny', 'Chinese Yuan'), ('sek', 'Swedish Krona'), ('nzd', 'New Zealand Dollar')], default='usd', help_text='Select the currency in which product price is displayed.', max_length=3)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('stock', models.IntegerField()),
                ('is_featured', models.BooleanField(default=False, help_text='Check this option if you want to highlight this productin main listings.')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx')],
            },
        ),
    ]
